- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: gce
        gce:
          project-id: ((project_id))
          network-name: ((network))
          worker-node-tag: ((director_name))-((deployment_name))-worker
    provides:
      cloud-provider: {as: master}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/consumes?
  value:
    cloud-provider: {from: master}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: gce
        gce:
          project-id: ((project_id))
          network-name: ((network))
          worker-node-tag: ((director_name))-((deployment_name))-worker