- type: replace
  path: /instance_groups/name=master/vm_type
  value: default

- type: replace
  path: /instance_groups/name=worker/vm_type
  value: default

- type: replace
  path: /instance_groups/name=master/azs
  value: [z1]

- type: replace
  path: /instance_groups/name=worker/azs
  value: [z1]

- type: remove
  path: /variables/name=tls-kubelet/options/organization

- type: remove
  path: /variables/name=tls-kubernetes/options/organization
