- type: replace
  path: /variables/name=tls-kubelet/options/common_name
  value: ((kubernetes_master_host))

- type: replace
  path: /variables/name=tls-kubelet/options/alternative_names
  value: [((kubernetes_master_host))]

- type: replace
  path: /variables/name=tls-kubernetes/options/common_name
  value: ((kubernetes_master_host))

- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/-
  value: ((kubernetes_master_host))

- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: kubernetes-api-route-registrar
    release: kubo
    properties:
      external_kubo_port: ((kubernetes_master_port))
      cloud_foundry:
        api_url: ((routing-cf-api-url))
        uaa_url: ((routing-cf-uaa-url))
        uaa_client_id: ((routing-cf-client-id))
        uaa_client_secret: ((routing-cf-client-secret))

- type: replace
  path: /instance_groups/-
  value:
    name: route-sync
    instances: 1
    networks:
    - name: default
    azs: [z1]
    jobs:
    - name: route-sync
      release: kubo
      properties:
        api-token: ((route-sync-password))
        tls:
          kubernetes: ((tls-kubernetes))
        cloud_foundry:
          uaa_url: ((routing-cf-uaa-url))
          routing_api_url: ((routing-cf-api-url))
          routing_api_client_id: ((routing-cf-client-id))
          routing_api_client_secret: ((routing-cf-client-secret))
          skip_tls_verification: true
          app_domain: ((routing-cf-app-domain-name))
        nats:
          machines: ((routing-cf-nats-internal-ips))
          port: ((routing-cf-nats-port))
          user: ((routing-cf-nats-username))
          password: ((routing-cf-nats-password))
    stemcell: trusty
    vm_type: minimal
